### ISSUE TITLE
如何获取模型的输出节点名称？

### ISSUE THREAD

**Issue by Tomhouxin** [Zheng222/IDN-tensorflow#2]
将ckpt转pb的时候，需要指定输出节点名字，这个如何得到？
![image](https://user-images.githubusercontent.com/23637856/56802591-01021a00-6853-11e9-99ae-015240eb723f.png)
使用这个代码得到的节点好像不完整

**Comment by Zheng222** [comment]
@Tomhouxin Hello, you can refer to [this code snippet](https://github.com/Zheng222/PPCN/blob/master/test/evaluate_super_resolution.py) to convert `ckpt` to `pb.`

**Comment by Tomhouxin** [comment]
When I run [this code](https://github.com/Zheng222/PPCN/blob/master/test/evaluate_super_resolution.py),and  instead [this ckpt](https://github.com/Zheng222/IDN-tensorflow/tree/master/checkpoint_x2), I get ERROR:
![image](https://user-images.githubusercontent.com/23637856/56857410-ad511700-699f-11e9-8d7e-cc8bc4f4fa16.png)
So, Can you provide your output node name of ckpt

**Comment by Zheng222** [comment]
@Tomhouxin Hello, I can convert `ckpt` to `pb` using the following code snippet. So, I recommend that you should carefully check your code.

![image](https://user-images.githubusercontent.com/24320162/56858244-96172700-69a9-11e9-80f1-4781fdddc80d.png)

![image](https://user-images.githubusercontent.com/24320162/56858235-84358400-69a9-11e9-9b0b-7e28c8d31841.png)
