### ISSUE TITLE
About data augmentation

### ISSUE THREAD

**Issue by lkyee** [Zheng222/IDN-tensorflow#3]
Hi,I found utils.py contains the function of augment,but train_SR.py doesn't use the funtion of augment like utils.augment.I feel confused.
Look forward to your kind reply.Thank you!

**Comment by Zheng222** [comment]
@lkyee https://github.com/Zheng222/IDN-tensorflow/blob/2a3012360a172ef6b8c8fc99caf7d4ad83850c10/train_SR.py#L119

https://github.com/Zheng222/IDN-tensorflow/blob/2a3012360a172ef6b8c8fc99caf7d4ad83850c10/utils.py#L26-L29

Hello, utils.crop_sub_imgs_fn includes augment function.

**Comment by lkyee** [comment]
Sorry,it is my fault.
Thank you very much!
