### ISSUE TITLE
network checkpoints for 3x and 4x doesn't work 

### ISSUE THREAD

**Issue by ShaharSarShalom** [Zheng222/IDN-tensorflow#8]
Hey 

The network checkpoints for 3x and 4x doesn't run properly 

I get this error 

`NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
Key IDN/2/conv2d/bias not found in checkpoint
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
`

would it be possible that you trained the x4 / x3 on a different network configuration?

**Comment by Zheng222** [comment]
@ShaharSarShalom Hello, I have tested x3 and x4 models on Set5. The checkpoints are ok.
![image](https://user-images.githubusercontent.com/24320162/77851193-3c972800-720a-11ea-8342-5415cbd17e0e.png)

![image](https://user-images.githubusercontent.com/24320162/77851209-56d10600-720a-11ea-9254-8951e1816281.png)

Please check out https://github.com/Zheng222/IDN-tensorflow/blob/2a3012360a172ef6b8c8fc99caf7d4ad83850c10/test.py#L15
and https://github.com/Zheng222/IDN-tensorflow/blob/2a3012360a172ef6b8c8fc99caf7d4ad83850c10/config.py#L24 are correct.
